### ISSUE TITLE
Request endpoint for health check kubernetes

### ISSUE THREAD

**Issue by abdidarmawan007** [amaurymartiny/check-if-email-exists#581]
Hi did you have endpoint GET give response 200

for example i need run in kubernetes and we need health check end point give response 200
for example /status or something ?
```
      readinessProbe:
         httpGet:
            path: /status
            port: 3000
        livenessProbe:
           httpGet:
             path: /status
             port: 3000
           initialDelaySeconds: 18
           periodSeconds: 10
```
